Updated MLJ interface for feature importances per #166
Evovest/EvoTrees.jl pull request #167
Opened 2022-09-29 17:46 UTC by john-waczak

2022-09-30 00:00 UTC, ablaom commented
@OkonSamuel

2022-09-30 01:19 UTC, jeremiedb requested changes
Thanks for bringin this PR! 
I've made some comments regarding suggested edits.

2022-09-30 01:19 UTC, jeremiedb commented on src/MLJ.jl
> +  report = ()
Shouldn't it return the feature names, same as in the above `fit` function? 
`report = (features=A.names,)`

2022-09-30 01:19 UTC, jeremiedb commented on src/MLJ.jl
> +#  report = (feature_importances=importance(fitresult, A.names),)
I'd remove the commented out line.

2022-09-30 01:19 UTC, jeremiedb commented on src/MLJ.jl
> +  # report = (feature_importances=importance(fitresult, A.names),)
Remove commentted out line.

2022-09-30 01:19 UTC, jeremiedb commented on src/MLJ.jl
> +    sort!(fi_pairs, by= x->-x[2])
Can be removed since `importance` already sort the feature in decreasing order.

2022-09-30 01:19 UTC, jeremiedb commented on src/MLJ.jl
> +MMI.reports_feature_importances(::Type{<:EvoTreeGaussian}) = true
Can be simplified by using `EvoTypes`: 
```julia
MMI.reports_feature_importances(::Type{<:EvoTypes}) = true
```

2022-09-30 06:07 UTC, john-waczak commented
@jeremiedb Comments should be gone now, update method is fixed, and I removed the repeated calls to `reports_feature_importances` per your suggestion. Please let me know if there's anything else I need to  tweak!

2022-10-03 04:36 UTC, jeremiedb commented
@john-waczak Thans for the update. Just for clarification, although I understand that MLJ provides a seperate `features importance` extractor function, was there actually a concern for having the feature importance calculated within the report? Is the reason to save compute time while iterating over a model?

2022-10-03 07:25 UTC, OkonSamuel commented
> @john-waczak Thans for the update. Just for clarification, although I understand that MLJ provides a seperate `features importance` extractor function, was there actually a concern for having the feature importance calculated within the report? Is the reason to save compute time while iterating over a model?

@jeremiedb MLJ intends to use that API to build other functionality such are recursive feature elimination etc. But it is still going to be accessible by the user when calling `feature_importances(mach::Machine)`. There is nothing stopping you from leaving feature importances in your report then just returning that again in when one calls `feature_importances(model, fitresult, report)`. 
Again, pushing the feature importances calculations to the `feature_importances` method can help to save some computation time. It is only computed when the user needs it.

2022-10-03 14:15 UTC, john-waczak commented
@jeremiedb @OkonSamuel I can add them back to the report if you prefer. I just figured with the newer extraction method it made sense to remove the duplicate in the report.

2022-10-03 15:17 UTC, jeremiedb approved these changes

2022-10-03 15:19 UTC, jeremiedb commented
I just wanted to make sure I understood the original motivation for the changes. Sounds good to me, thanks for @john-waczak and @OkonSamuel for the clarifications.

2022-10-03 15:19 UTC, merged

2022-10-04 23:23 UTC, ablaom commented
Just wanted to be sure that the importances returned has the correct form. Is an `AbstractVector` ([required](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Feature-importances)) or `Tuple` of pairs returned? In any case, I suggest explicitly testing the importances have the required form.

2022-10-04 23:24 UTC, ablaom commented
Okay, I didn't update my page and now see this is merged with a review from Samuel, so all should be good.